// <auto-generated />
using System;
using LGUTreasury.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGUTreasury.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528161153_AddIsDeletedToPaymentRecord")]
    partial class AddIsDeletedToPaymentRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LGUTreasury.Models.AccountBillingType", b =>
                {
                    b.Property<int>("AccountBillingTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BillingTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LongTermPayeeID")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("AccountBillingTypeID");

                    b.HasIndex("LongTermPayeeID");

                    b.ToTable("AccountBillingTypes");
                });

            modelBuilder.Entity("LGUTreasury.Models.BillingTypeOption", b =>
                {
                    b.Property<int>("BillingTypeOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BillingTypeOptionID");

                    b.ToTable("BillingTypeOptions");
                });

            modelBuilder.Entity("LGUTreasury.Models.DeletedRecord", b =>
                {
                    b.Property<int>("DeletedRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CollectionType")
                        .HasColumnType("longtext");

                    b.Property<string>("CollectorName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy_UserID")
                        .HasColumnType("int");

                    b.Property<string>("PayeeName")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentRecordPaymentID")
                        .HasColumnType("int");

                    b.HasKey("DeletedRecordID");

                    b.HasIndex("DeletedByUserID");

                    b.HasIndex("PaymentRecordPaymentID");

                    b.ToTable("DeletedRecords");
                });

            modelBuilder.Entity("LGUTreasury.Models.EditRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestedBy_UserID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedBy_UserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RequestID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("RequestedBy_UserID");

                    b.HasIndex("ReviewedBy_UserID");

                    b.ToTable("Editrequests");
                });

            modelBuilder.Entity("LGUTreasury.Models.LongTermPayee", b =>
                {
                    b.Property<int>("LongTermPayeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("BillGenerationDay")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("StartMonth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext");

                    b.HasKey("LongTermPayeeID");

                    b.ToTable("LongTermPayees");
                });

            modelBuilder.Entity("LGUTreasury.Models.MonthlyBill", b =>
                {
                    b.Property<int>("MonthlyBillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountBillingTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("BilledAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("BillingMonth")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LongTermPayeeID")
                        .HasColumnType("int");

                    b.Property<string>("ORNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MonthlyBillID");

                    b.HasIndex("AccountBillingTypeID");

                    b.HasIndex("LongTermPayeeID");

                    b.ToTable("MonthlyBills");
                });

            modelBuilder.Entity("LGUTreasury.Models.Payee", b =>
                {
                    b.Property<int>("PayeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Middlename")
                        .HasColumnType("longtext");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext");

                    b.HasKey("PayeeID");

                    b.ToTable("Payees");
                });

            modelBuilder.Entity("LGUTreasury.Models.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollectedBy_UserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CollectedConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasPendingRequest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OfficialReceipt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PayeeID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalBaseAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalSurcharge")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("PaymentID");

                    b.HasIndex("CollectedBy_UserID");

                    b.HasIndex("PayeeID");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("LGUTreasury.Models.RecordLineItem", b =>
                {
                    b.Property<int>("LineItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SurchargeAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("LineItemID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("TypeID");

                    b.ToTable("RecordLineItems");
                });

            modelBuilder.Entity("LGUTreasury.Models.ReportLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GeneratedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LogID");

                    b.ToTable("ReportLog");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenueCategory", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryID");

                    b.ToTable("RevenueCategories");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenuePolicy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SurchargeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("PolicyID");

                    b.HasIndex("TypeID");

                    b.ToTable("RevenuePolicies");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenueType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrdinanceSection")
                        .HasColumnType("longtext");

                    b.HasKey("TypeID");

                    b.HasIndex("CategoryID");

                    b.ToTable("RevenueTypes");
                });

            modelBuilder.Entity("LGUTreasury.Models.UserAccount", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("LGUTreasury.Models.AccountBillingType", b =>
                {
                    b.HasOne("LGUTreasury.Models.LongTermPayee", "LongTermPayee")
                        .WithMany("AccountBillingTypes")
                        .HasForeignKey("LongTermPayeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LongTermPayee");
                });

            modelBuilder.Entity("LGUTreasury.Models.DeletedRecord", b =>
                {
                    b.HasOne("LGUTreasury.Models.UserAccount", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByUserID");

                    b.HasOne("LGUTreasury.Models.PaymentRecord", "PaymentRecord")
                        .WithMany()
                        .HasForeignKey("PaymentRecordPaymentID");

                    b.Navigation("DeletedBy");

                    b.Navigation("PaymentRecord");
                });

            modelBuilder.Entity("LGUTreasury.Models.EditRequest", b =>
                {
                    b.HasOne("LGUTreasury.Models.PaymentRecord", "PaymentRecord")
                        .WithMany("EditRequests")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGUTreasury.Models.UserAccount", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedBy_UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGUTreasury.Models.UserAccount", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedBy_UserID");

                    b.Navigation("PaymentRecord");

                    b.Navigation("RequestedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("LGUTreasury.Models.MonthlyBill", b =>
                {
                    b.HasOne("LGUTreasury.Models.AccountBillingType", "AccountBillingType")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("AccountBillingTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGUTreasury.Models.LongTermPayee", "LongTermPayee")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("LongTermPayeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountBillingType");

                    b.Navigation("LongTermPayee");
                });

            modelBuilder.Entity("LGUTreasury.Models.PaymentRecord", b =>
                {
                    b.HasOne("LGUTreasury.Models.UserAccount", "CollectedBy")
                        .WithMany()
                        .HasForeignKey("CollectedBy_UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGUTreasury.Models.Payee", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectedBy");

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("LGUTreasury.Models.RecordLineItem", b =>
                {
                    b.HasOne("LGUTreasury.Models.PaymentRecord", "PaymentRecord")
                        .WithMany("RecordLineItems")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGUTreasury.Models.RevenueType", "RevenueType")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRecord");

                    b.Navigation("RevenueType");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenuePolicy", b =>
                {
                    b.HasOne("LGUTreasury.Models.RevenueType", "RevenueType")
                        .WithMany("RevenuePolicies")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RevenueType");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenueType", b =>
                {
                    b.HasOne("LGUTreasury.Models.RevenueCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LGUTreasury.Models.AccountBillingType", b =>
                {
                    b.Navigation("MonthlyBills");
                });

            modelBuilder.Entity("LGUTreasury.Models.LongTermPayee", b =>
                {
                    b.Navigation("AccountBillingTypes");

                    b.Navigation("MonthlyBills");
                });

            modelBuilder.Entity("LGUTreasury.Models.PaymentRecord", b =>
                {
                    b.Navigation("EditRequests");

                    b.Navigation("RecordLineItems");
                });

            modelBuilder.Entity("LGUTreasury.Models.RevenueType", b =>
                {
                    b.Navigation("RevenuePolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
